version: "3.8"

volumes:
  postgres-volume:

networks:
  postgres-network:
    driver: bridge

services:
  project:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 3.10-bullseye
        USERNAME: vscode
        USER_UID: 1000
    init: true
    ports:
      - 3109:3109
    env_file:
      - ../.env
    volumes:
      - ..:/workspace:cached
    networks:
      - postgres-network
    command: sleep infinity
    user: vscode

  postgres:
    image: postgres:14.2-bullseye
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - ../.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - postgres-network
